name: docker-react

services:
- name: web
  image:
    registry: registry.digitalocean.com
    registry_type: DOCKER_REGISTRY
    repository: docker-react
    tag: latest
  http_port: 80
  envs:
    - key: CI
      value: "true"
