name: docker-react

services:
- name: web
  image:
    registry: registry.digitalocean.com
    registry_type: DOCKER_REGISTRY
    repository: ${DO_REGISTRY_USERNAME}/docker-react
    tag: latest
  http_port: 80
  health_check:
    http_path: /
    port: 80
  envs:
    - key: CI
      value: "true"