name: docker-react

services:
- name: web
  github:
    repo: stangatimu/docker-react
    branch: main
  build_command: npm run build
  http_port: 3000
  envs:
    - key: CI
      value: "true"
  dockerfile_path: Dockerfile
  source_dir: /
